<?php
/**
 * Created by PhpStorm.
 * User: 梓晨<1251251214@qq.com>
 * Date: 2017/9/4
 * Time: 13:20
 */

namespace app\index\controller;


class Ajax extends Common
{

    protected function _initialize()
    {
        config('default_return_type', 'json');//JSON格式输出
        $this->returnType = 'json';
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}